### PR TITLE
Resize height of video container 

### PR DESCRIPTION
**Pull request by tsivert**
When aspect ratio is provided, resize the height of the video container to reflect the size of the video.

### CODE REVIEW

**Comment by icc** [comment]
Although it's not fully clear to me what we want to achieve here, it feels good to get more metadata on the video files, However, I do believe that the solution could be made much more flexible. Seeing as not all videos and players will fit within one on those 4-5 defined aspect ratios here. Since this is a WYSIWYG editor, why not just get the size/aspect of the video when it loads the first time and then use that?
This should also make it possible to take into consideration fixed video controls at the bottom of the video.

**Comment by tsivert** [comment]
Hi.
When images are inserted into a CP the image is displayed with a calculated aspect ratio based on the provided height and width. The thinking with this is to add the same feature to videos. When a video is inserted with accompanying aspect ratio, the container that contains the video is resized according to the provided aspect ratio. 

As I understand the code in CP all the dimensions of inserted elements are set based on the height, width and slide ratio. Due to this I can't resize the container when the video loads. Or can I? If yes, then you will have a different display between the editor and the "front" rendering of the CP(if I understood your point correct). And that's not good.

The reason for the defined aspect ratios is that I'm not aware of any standard way of getting the height and/or width of a video(given that it's not a html5 video tag). In the cases where the video is a Youtube video, the height is set to be the width of the wrapper multiplied with 9/16(line 59 in youtube.js in H5P.Video 1.5). This means that in the current version the aspect ratio is not kept as the container width is set in CP editor with no knowledge of the height. 
And yes, not all will fit within. But since this is a "missing feature" I figured that it's a good place to start. The provided ratios are the "most commonly" up until now.
And last but not least, if no aspect ratio is provided, the sizing works as it currently does.

See the screenshots below. Notice the top an bottom. In the last image I've increased the height of the container surrounding the video underlining the point that the aspect ratio is not kept. The video has not re-rendered but still shows more than the first one.
CP with current height logic
CP with current height logic 2

**Comment by icc** [comment]
I see the "fit" parameter is always set which makes my suggested solution cumbersome. I was thinking we could just set the width and then update the height when the preview rendered(listening to the 'resize' event of the instance). But seeing as "fit" is always set we would just get black bars/margins instead.

Anyway, do you it's possible to just drop the "whitelist" and support any aspect ratio? e.g.
```js
const wh = String(fileParams.aspectRatio).split(':');
elementParams.height = (elementParams.width * (wh.length === 1 ? fileParams.aspectRatio : (wh[1] / wh[0]))) * this.slideRatio;
```

Also, it would be nice if 16:9 was the default when adding a video in case the aspect ratio is missing e.g. by adding the following to [addElement](https://github.com/h5p/h5p-editor-course-presentation/blob/master/scripts/cp-editor.js#L161):
```js
case 'H5P.Video':
case 'H5P.InteractiveVideo':
  elementParams.width = 48;
  elementParams.height = 27;
  break;
```
I can't imagine that today's default(1:1) is very useful to many.

**Comment by tsivert** [comment]
Thanks for the feedback. I'll make the changes and update the PR.

**Comment by tsivert** [comment]
I tried to use the elementParams width and height to calculate the ratio based on that. And when inserting a video that worked. But when you edit/replaced an existing video the height had changed from the initial height to the calculated one, but not the width. The ratio was then broken. I therefore set a default aspect ratio of 16:9, as you mentioned, and calculate the height based on that.
If [this](https://github.com/h5p/h5p-editor-php-library/pull/68) PR gets approved then aspect ratio is provided as a field that can be set for each provider.

**Comment by icc** [comment]
Good work, I think this will be useful to many.

**Comment by tsivert** [comment]
Thanks! :)

**Pull request merged**
